name: Feature Request
description: Suggest a new rule or feature for Vue Best Practices
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature are you suggesting?
      options:
        - New performance rule
        - Documentation improvement
        - Tooling enhancement
        - Other
    validations:
      required: true

  - type: input
    id: category
    attributes:
      label: Category
      description: Which category does this belong to?
      placeholder: "e.g., reactivity, rendering, bundle, etc."

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to be solved?
      placeholder: "I would like..."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, provide code examples
      placeholder: |
        ```vue
        // Your example code here
        ```
      render: markdown

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: "I've also considered..."

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact Level
      description: What performance impact would this have?
      options:
        - CRITICAL
        - HIGH
        - MEDIUM-HIGH
        - MEDIUM
        - LOW-MEDIUM
        - LOW
        - Not sure

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant documentation, articles, or discussions
      placeholder: |
        - https://vuejs.org/...
        - https://example.com/...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with Vue/Nuxt best practices
          required: true
        - label: I can provide real-world examples if needed
          required: true
